/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import controller.Controller;
import domain.Clanarina;
import domain.IndividualniTrening;
import domain.Nalog;
import domain.Teretana;
import domain.Trener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Forma za zakazivanje individualnih treninga
 * 
 * @author Luka
 */
public class FrmIndividualniTrening extends javax.swing.JFrame {

    Nalog n;
    
    /**
     * Creates new form FrmIndividualniTrening
     */
    public FrmIndividualniTrening(Nalog n) {
        initComponents();
        this.n = n;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        popuniFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jcbTeretana = new javax.swing.JComboBox<>();
        jcbTrener = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTermin = new javax.swing.JTextField();
        btnPotvrdi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Teretana:");

        jcbTeretana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTeretana.setSelectedIndex(-1);

        jcbTrener.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTrener.setSelectedIndex(-1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Trener:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Termin:");

        btnPotvrdi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPotvrdi.setText("Sačuvaj");
        btnPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTeretana, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTermin)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbTeretana, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTermin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdiActionPerformed
        IndividualniTrening it = vratiIndividualniTrening();
        try { 
            if(it != null){
                Controller.getInstance().dodajIndividualniTrening(it);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio trening");
            }else{
                JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti trening");
            } 
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti trening");
            Logger.getLogger(FrmIndividualniTrening.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPotvrdiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPotvrdi;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jcbTeretana;
    private javax.swing.JComboBox<String> jcbTrener;
    private javax.swing.JTextField txtTermin;
    // End of variables declaration//GEN-END:variables

    /**
     * Popunjva formu podacima
     */
    private void popuniFormu() {
        List<Teretana> teretane;
        
        try {
            //teretane = Controller.getInstance().vratiSveTeretane();
            
            teretane = vratiTeretaneSaClanarinom();
            
            jcbTeretana.setModel(new DefaultComboBoxModel(teretane.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(FrmIndividualniTrening.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jcbTrener.setEnabled(false);
        
        jcbTeretana.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    Teretana t = (Teretana) jcbTeretana.getSelectedItem();
                    List<Trener> treneri = new ArrayList<>();
                    treneri = Controller.getInstance().nadjiTrenere(t);
                    jcbTrener.setEnabled(true);
                    jcbTrener.setModel(new DefaultComboBoxModel(treneri.toArray()));
                } catch (Exception ex) {
                    Logger.getLogger(FrmOprema.class.getName()).log(Level.SEVERE, null, ex);
                    jcbTrener.setModel(new DefaultComboBoxModel(new ArrayList().toArray()));
                }
            }
        });
        
    }

    private List<Teretana> vratiTeretaneSaClanarinom() {
    	List<Clanarina> clanarine = new ArrayList<>();
    	List<Teretana> teretane = new ArrayList<>();
    	
    	try {
    		clanarine = Controller.getInstance().vratiSveClanarine(n);	
    		for(int i = 0; i < clanarine.size(); i++)
    			teretane.add(clanarine.get(i).getTeretana());
		} catch (Exception e) {
			e.printStackTrace();
		}
    	
		return teretane;
	}

	/**
     * Vraca individualni trening na osnovu podataka unetih u formu
     * 
     * @return individualni trening
     */
    private IndividualniTrening vratiIndividualniTrening() {
        IndividualniTrening it = new IndividualniTrening();
        it.setNalog(n);
        
        Trener t = (Trener) jcbTrener.getSelectedItem();        
        it.setTrener(t);
        it.setTermin(LocalDate.parse(txtTermin.getText(), DateTimeFormatter.ofPattern("yyyy-MM-dd")));
        
        return it;        
    }
}
