/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import controller.Controller;
import domain.Grad;
import domain.Teretana;
import domain.Trener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import view.form.util.FormMode;

/**
 * Forma za kreiranje novog trenera
 * 
 * @author Luka
 */
public class FrmNoviTrener extends javax.swing.JFrame {

    Trener trener;
    FormMode fm;
    
    /**
     * Creates new form FrmNoviTrener
     */
    public FrmNoviTrener(FormMode fm) {
        initComponents();
        
        this.fm = fm;
        trener = new Trener();
        
        popuniFormu(fm);
    }
    
    public FrmNoviTrener(Trener trener, FormMode fm) {
        initComponents();
        
        this.trener = trener;
        
        popuniFormu(fm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbGrad = new javax.swing.JComboBox<>();
        jcbTeretana = new javax.swing.JComboBox<>();
        btnPotvrdi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcbGrad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbGrad.setSelectedIndex(-1);

        jcbTeretana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTeretana.setSelectedIndex(-1);

        btnPotvrdi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPotvrdi.setText("Sačuvaj");
        btnPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ime:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Prezime:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Teretana:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Grad:");

        txtPrezime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtIme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbTeretana, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbGrad, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbTeretana, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdiActionPerformed
        Trener t = vratiZapamcenogTrenera();
        if(t != null){
            try {
                zapamtiTrenera(t);
                JOptionPane.showMessageDialog(this, "Sistem je zapamtio teretanu");
            } catch (Exception ex) {
                Logger.getLogger(FrmNoviTrener.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti teretanu");
        }
    }//GEN-LAST:event_btnPotvrdiActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPotvrdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jcbGrad;
    private javax.swing.JComboBox<String> jcbTeretana;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    /**
     * Popunjava formu podacima na osnovu rezima forme
     * 
     * @param fm rezim forme
     */
    private void popuniFormu(FormMode fm) {
        
        List<Grad> gradovi;        
        try {
            gradovi = Controller.getInstance().vratiSveGradove();
            jcbGrad.setModel(new DefaultComboBoxModel(gradovi.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(FrmNoviTrener.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(fm == FormMode.FORM_EDIT){
            txtIme.setText(trener.getIme());
            txtPrezime.setText(trener.getPrezime());
            
            txtIme.setEditable(false);
            txtPrezime.setEditable(false);
            //btnPotvrdi.setEnabled(false);
        }
        if(fm == FormMode.FORM_ADD){
            txtIme.setEditable(true);
            txtPrezime.setEditable(true);
        }
        
        jcbGrad.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                try {
                    Grad g = (Grad) jcbGrad.getSelectedItem();
                    List<Teretana> teretane = Controller.getInstance().nadjiTeretane(g);
                    jcbTeretana.setEnabled(true);
                    jcbTeretana.setModel(new DefaultComboBoxModel(teretane.toArray()));
                } catch (Exception ex) {
                    Logger.getLogger(FrmOprema.class.getName()).log(Level.SEVERE, null, ex);
                    jcbTeretana.setModel(new DefaultComboBoxModel(new ArrayList().toArray()));
                }
            }
        });
    }

    /**
     * Vraca trenera zapamcenog u bazi podataka
     * 
     * @return trener zapamcen u bazi podataka
     */
    private Trener vratiZapamcenogTrenera() {
        trener.setIme(txtIme.getText());
        trener.setPrezime(txtPrezime.getText());
        
        Teretana teretana = (Teretana) jcbTeretana.getSelectedItem();
        trener.setTeretana(teretana);
        return trener;
    }

    /**
     * Pamti trenera u bazi podataka
     * 
     * @param t trener
     * @throws Exception 
     */
    private void zapamtiTrenera(Trener t) throws Exception {
        if(fm == FormMode.FORM_ADD)
            Controller.getInstance().dodajTrenera(t);
        else
            Controller.getInstance().urediTrenera(t);
    }
    
    
    
}