/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import controller.Controller;
import domain.Grad;
import domain.Teretana;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.form.component.table.TeretanaTableModel;
import view.form.component.table.TrenerTableModel;

/**
 * Forma za pregled svih teretana u odredjenom gradu, koja dozvoljava kreiranje nove teretane i prikaz trenera u teretani
 * 
 * @author Luka
 */
public class FrmPregledTeretana extends javax.swing.JFrame {

    Teretana t;
    List<Teretana> teretane;
    
    /**
     * Creates new form FrmPregledTeretana
     */
    public FrmPregledTeretana() {
        initComponents();
        
        t = new Teretana();
        teretane = new ArrayList<>();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        popuniFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeretane = new javax.swing.JTable();
        btnPretraga = new javax.swing.JButton();
        jcbGrad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnKreirajTeretanu = new javax.swing.JButton();
        btnTrener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTeretane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTeretane);

        btnPretraga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPretraga.setText("Pretraži");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        jcbGrad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbGrad.setSelectedIndex(-1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Grad:");

        btnKreirajTeretanu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKreirajTeretanu.setText("Kreiraj teretanu");
        btnKreirajTeretanu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajTeretanuActionPerformed(evt);
            }
        });

        btnTrener.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTrener.setText("Prikaži trenere");
        btnTrener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jcbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKreirajTeretanu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTrener)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreirajTeretanu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrener, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        Grad g = (Grad) jcbGrad.getSelectedItem();
        List<Teretana> list = new ArrayList<>();
        try {
            list = Controller.getInstance().nadjiTeretane(g);
        } catch (Exception ex) {
            Logger.getLogger(FrmPregledTeretana.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblTeretane.setModel(new TeretanaTableModel(list));
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnKreirajTeretanuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajTeretanuActionPerformed
       new FrmTeretana().setVisible(true);
    }//GEN-LAST:event_btnKreirajTeretanuActionPerformed

    private void btnTrenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrenerActionPerformed
        if(tblTeretane.getSelectedRow() != -1){
            try {
                t = teretane.get(tblTeretane.getSelectedRow());                
                new FrmTrener(t).setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita teretanu");
                Logger.getLogger(FrmClanarina.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Izaberite teretanu");
        }        
    }//GEN-LAST:event_btnTrenerActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKreirajTeretanu;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnTrener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbGrad;
    private javax.swing.JTable tblTeretane;
    // End of variables declaration//GEN-END:variables

    /**
     * Popunjva formu podacima
     */
    private void popuniFormu() {
        jcbGrad.setSelectedIndex(-1);
        
        List<Grad> gradovi = new ArrayList<>();
        
        try {
            gradovi = Controller.getInstance().vratiSveGradove();
            jcbGrad.setModel(new DefaultComboBoxModel(gradovi.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(FrmPregledTeretana.class.getName()).log(Level.SEVERE, null, ex);
        }
        popuniTabelu();
    }
    
    /**
     * Popunjva tabelu teretana
     */
    private void popuniTabelu() {
        try {
            teretane = Controller.getInstance().vratiSveTeretane();
            tblTeretane.setModel(new TeretanaTableModel(teretane));
        } catch (Exception ex) {
            Logger.getLogger(FrmTrener.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
